In [2]:
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [3]:
df=pd.read_csv("insulindataset.csv")

In [4]:
df.head()

age  bloodglucose                  food  servings     Cho  TDDI    ISF  \
0   13           212                  DOSA         4  116.00    23  78.26   
1   13            78       CHAPATI + KURMA         3   56.00    24  75.00   
2   13           146  CHAPATI + FISH CURRY         4   72.00    22  81.81   
3   13           530      CHAPATI  + KURMA         4   71.00    22  81.81   
4   12           120           RICE + OKRA         2  114.34    20  90.00   

   insulin  
0        5  
1        4  
2        5  
3       10  
4        4

In [5]:
df.corr()

age  bloodglucose  servings       Cho      TDDI       ISF  \
age           1.000000      0.234173  0.135713  0.089418  0.194212 -0.181338   
bloodglucose  0.234173      1.000000 -0.063588 -0.101692  0.246081 -0.229791   
servings      0.135713     -0.063588  1.000000 -0.295993  0.097592 -0.098713   
Cho           0.089418     -0.101692 -0.295993  1.000000 -0.015188  0.000078   
TDDI          0.194212      0.246081  0.097592 -0.015188  1.000000 -0.989684   
ISF          -0.181338     -0.229791 -0.098713  0.000078 -0.989684  1.000000   
insulin       0.272343      0.698154  0.039717  0.182280  0.463436 -0.456031   

               insulin  
age           0.272343  
bloodglucose  0.698154  
servings      0.039717  
Cho           0.182280  
TDDI          0.463436  
ISF          -0.456031  
insulin       1.000000

In [7]:
#import seaborn as sns
#sns.pairplot(df)

In [6]:
df.head()

age  bloodglucose                  food  servings     Cho  TDDI    ISF  \
0   13           212                  DOSA         4  116.00    23  78.26   
1   13            78       CHAPATI + KURMA         3   56.00    24  75.00   
2   13           146  CHAPATI + FISH CURRY         4   72.00    22  81.81   
3   13           530      CHAPATI  + KURMA         4   71.00    22  81.81   
4   12           120           RICE + OKRA         2  114.34    20  90.00   

   insulin  
0        5  
1        4  
2        5  
3       10  
4        4

In [7]:
dataset=df.drop(['food','servings'],axis=1)
dataset

age  bloodglucose     Cho  TDDI     ISF  insulin
0    13           212  116.00    23   78.26        5
1    13            78   56.00    24   75.00        4
2    13           146   72.00    22   81.81        5
3    13           530   71.00    22   81.81       10
4    12           120  114.34    20   90.00        4
..  ...           ...     ...   ...     ...      ...
95   10            95   87.00    21   85.71        3
96   10            87   56.00    21   85.71        3
97   10            88   41.00    21   85.71        3
98   11            95   74.00    16  112.50        3
99   11            89   57.60    16  112.50        3

[100 rows x 6 columns]

In [8]:
X=dataset.iloc[:,:-1]
Y=dataset.iloc[:,-1]
X

age  bloodglucose     Cho  TDDI     ISF
0    13           212  116.00    23   78.26
1    13            78   56.00    24   75.00
2    13           146   72.00    22   81.81
3    13           530   71.00    22   81.81
4    12           120  114.34    20   90.00
..  ...           ...     ...   ...     ...
95   10            95   87.00    21   85.71
96   10            87   56.00    21   85.71
97   10            88   41.00    21   85.71
98   11            95   74.00    16  112.50
99   11            89   57.60    16  112.50

[100 rows x 5 columns]

In [9]:
Y

0      5
1      4
2      5
3     10
4      4
      ..
95     3
96     3
97     3
98     3
99     3
Name: insulin, Length: 100, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [13]:
X_train=scaler.fit_transform(X_train)

In [14]:
X_test=scaler.transform(X_test)

In [15]:
X_train

array([[ 2.50367018e-01, -4.56366254e-01,  2.03882502e-01,
        -1.86594608e+00,  2.02588788e+00],
       [ 2.50367018e-01, -6.84316779e-01,  1.92722726e+00,
         3.37219171e-01, -4.25196950e-01],
       [ 2.50367018e-01, -4.56366254e-01,  8.89303711e-01,
         3.37219171e-01, -4.25196950e-01],
       [-8.44988684e-01,  8.62490352e-01,  1.30708426e+00,
        -1.86594608e+00,  2.02588788e+00],
       [ 2.50367018e-01,  3.25178401e-01, -2.85704076e-01,
         9.66694957e-01, -8.73321689e-01],
       [-1.94034439e+00, -9.12267303e-01,  2.03882502e-01,
        -2.92256615e-01,  1.08114439e-01],
       [ 2.50367018e-01,  3.74024942e-01,  1.92722726e+00,
         6.51957064e-01, -6.58565424e-01],
       [-1.94034439e+00, -6.35470238e-01, -1.29751634e+00,
        -2.92256615e-01,  1.08114439e-01],
       [ 2.50367018e-01,  5.04282385e-01, -3.18343181e-01,
         2.24812781e-02, -1.71068704e-01],
       [ 1.34572272e+00,  3.08896221e-01, -2.45912344e-02,
         2.24812781e-02

In [16]:
X_test

array([[ 0.25036702,  0.06466352, -0.75570719, -1.86594608,  2.02588788],
       [-0.84498868, -0.11444047, -0.28570408, -1.86594608,  2.02588788],
       [ 0.25036702,  2.86519853, -1.46071186,  0.96669496, -0.87332169],
       [ 1.34572272,  1.18813396, -1.46071186,  0.96669496, -0.87332169],
       [ 0.25036702,  0.22748532,  1.92722726,  0.65195706, -0.65856542],
       [-1.94034439, -0.39123753, -0.75570719, -0.29225662,  0.10811444],
       [ 1.34572272, -0.45636625, -0.28570408,  0.33721917, -0.42519695],
       [ 0.25036702, -0.89598512,  1.99250547,  0.33721917, -0.42519695],
       [ 1.34572272, -0.19585137,  1.22548649, -1.86594608,  2.02588788],
       [ 1.34572272,  0.30889622, -0.28570408,  0.02248128, -0.1710687 ],
       [ 0.25036702,  1.13928742, -1.56842091,  1.59617074, -1.25558784],
       [ 0.25036702,  0.01581698,  0.2038825 ,  0.65195706, -0.65856542],
       [ 0.25036702,  0.26004968, -1.46071186,  0.96669496, -0.87332169],
       [ 0.25036702,  0.4065893 ,  0.4

In [17]:
from sklearn.ensemble import RandomForestClassifier
random_forest_model=RandomForestClassifier(random_state=10)
random_forest_model.fit(X_train,Y_train.ravel())

RandomForestClassifier(random_state=10)

In [18]:
predict_train_data=random_forest_model.predict(X_test)

In [19]:
predict_train_data

array([4, 4, 4, 5, 5, 3, 4, 4, 3, 5, 5, 4, 5, 5, 4, 5, 3, 5, 3, 6, 4, 5,
       5, 3, 4, 4, 4, 3, 4, 5], dtype=int64)

In [20]:
from sklearn.metrics import r2_score
score=r2_score(Y_test,predict_train_data)
print(score)

0.4141578519121235


In [22]:
age=12
bloodglucose=90
Cho=95
TDDI=24
ISF=75

scaler.transform([[age,bloodglucose,Cho,TDDI,ISF]])

e:\Miniprjt\InsulinBuddy\venv\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([[ 0.25036702, -0.60290588,  0.46499534,  0.65195706, -0.65856542]])

In [24]:
value=random_forest_model.predict(scaler.transform([[age,bloodglucose,Cho,TDDI,ISF]]))
value

e:\Miniprjt\InsulinBuddy\venv\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([4], dtype=int64)

In [30]:
import pickle

In [31]:
pickle.dump(random_forest_model,open('regmodel.pkl','wb'))

In [32]:
pickled_model=pickle.load(open('regmodel.pkl','rb'))

In [33]:
pickled_model.predict(scaler.transform([[age,bloodglucose,Cho,TDDI,ISF]]))

e:\Miniprjt\InsulinBuddy\venv\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([4], dtype=int64)